-- Core OLTP schema for the commerce platform.
-- Dedicated schema (not public) keeps Debezium's schema.include.list clean
-- and makes per-role GRANTs simple (section 34: separate ingestion/analytics users).

CREATE SCHEMA IF NOT EXISTS commerce;

-- ---------------------------------------------------------------------------
-- warehouses (not in spec's required entity list, but a real FK target for
-- inventory.warehouse_id beats a bare unconstrained integer)
-- ---------------------------------------------------------------------------
CREATE TABLE commerce.warehouses (
    warehouse_id   SERIAL PRIMARY KEY,
    warehouse_name VARCHAR(100) NOT NULL,
    city           VARCHAR(100) NOT NULL
);

-- ---------------------------------------------------------------------------
-- customers
-- ---------------------------------------------------------------------------
CREATE TABLE commerce.customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    city        VARCHAR(100),
    country     VARCHAR(100),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- products
-- ---------------------------------------------------------------------------
CREATE TABLE commerce.products (
    product_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name   VARCHAR(255) NOT NULL,
    category       VARCHAR(100) NOT NULL,
    price          NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
    stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_products_category ON commerce.products (category);

-- ---------------------------------------------------------------------------
-- orders
-- discount_amount intentionally NOT present here -- introduced in Phase 4 as
-- the schema-evolution demonstration, once a live CDC pipeline exists to
-- observe it propagate (see docs/decisions/0002-schema-evolution-timing.md).
-- ---------------------------------------------------------------------------
CREATE TABLE commerce.orders (
    order_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT NOT NULL REFERENCES commerce.customers (customer_id),
    order_status VARCHAR(20) NOT NULL DEFAULT 'PLACED'
        CHECK (order_status IN ('PLACED', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_orders_customer_id ON commerce.orders (customer_id);
CREATE INDEX idx_orders_status ON commerce.orders (order_status);
CREATE INDEX idx_orders_updated_at ON commerce.orders (updated_at);

-- ---------------------------------------------------------------------------
-- order_items
-- ---------------------------------------------------------------------------
CREATE TABLE commerce.order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT NOT NULL REFERENCES commerce.orders (order_id),
    product_id    BIGINT NOT NULL REFERENCES commerce.products (product_id),
    quantity      INTEGER NOT NULL CHECK (quantity > 0),
    unit_price    NUMERIC(10, 2) NOT NULL CHECK (unit_price >= 0),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_order_items_order_id ON commerce.order_items (order_id);
CREATE INDEX idx_order_items_product_id ON commerce.order_items (product_id);

-- ---------------------------------------------------------------------------
-- payments
-- ---------------------------------------------------------------------------
CREATE TABLE commerce.payments (
    payment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT NOT NULL REFERENCES commerce.orders (order_id),
    payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (payment_status IN ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED')),
    payment_method VARCHAR(30) NOT NULL
        CHECK (payment_method IN ('CREDIT_CARD', 'DEBIT_CARD', 'UPI', 'NET_BANKING', 'WALLET', 'COD')),
    amount         NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_payments_order_id ON commerce.payments (order_id);

-- ---------------------------------------------------------------------------
-- inventory
-- ---------------------------------------------------------------------------
CREATE TABLE commerce.inventory (
    inventory_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT NOT NULL REFERENCES commerce.products (product_id),
    warehouse_id        INTEGER NOT NULL REFERENCES commerce.warehouses (warehouse_id),
    available_quantity  INTEGER NOT NULL DEFAULT 0 CHECK (available_quantity >= 0),
    reserved_quantity   INTEGER NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (product_id, warehouse_id)
);

CREATE INDEX idx_inventory_product_id ON commerce.inventory (product_id);
CREATE INDEX idx_inventory_warehouse_id ON commerce.inventory (warehouse_id);

-- ---------------------------------------------------------------------------
-- shipments
-- delivered_at >= shipped_at is enforced here so downstream data-quality
-- checks (Phase 3) are validating a source that's clean by construction.
-- ---------------------------------------------------------------------------
CREATE TABLE commerce.shipments (
    shipment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL REFERENCES commerce.orders (order_id),
    shipment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (shipment_status IN ('PENDING', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED', 'RETURNED')),
    carrier         VARCHAR(50),
    shipped_at      TIMESTAMPTZ,
    delivered_at    TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (delivered_at IS NULL OR shipped_at IS NULL OR delivered_at >= shipped_at)
);

CREATE INDEX idx_shipments_order_id ON commerce.shipments (order_id);

-- ---------------------------------------------------------------------------
-- Role grants (roles created in 01_roles.sh, before this schema existed)
-- ---------------------------------------------------------------------------
GRANT USAGE ON SCHEMA commerce TO commerce_app, debezium, commerce_readonly;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA commerce TO commerce_app;
-- UPDATE (not just USAGE/SELECT) is required for setval(), which the bulk
-- loader uses to resync identity sequences past explicit-ID COPY inserts.
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA commerce TO commerce_app;

-- Debezium needs SELECT for its initial snapshot; replication privilege
-- (granted at role level in 01_roles.sh) covers WAL streaming.
GRANT SELECT ON ALL TABLES IN SCHEMA commerce TO debezium;

GRANT SELECT ON ALL TABLES IN SCHEMA commerce TO commerce_readonly;
